name: test

on:
  push:
    branches:
      - master
      - main
      - dev
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:  # run CI on commits to any open PR
  workflow_dispatch:  # can manually trigger CI from GitHub actions tab

jobs:
  test:
    name: ${{ matrix.os }} ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment_cpu.yaml

      - name: Install pytest
        shell: bash -l {0}
        run: |
          python -m pip install pytest
          python -m pip install pytest-cov

      - name: Install package
        shell: bash -l {0}
        run: pip install --no-deps -e .

      - name: Run tests
        shell: bash -l {0}
        run: pytest

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          verbose: false
          fail_ci_if_error: false
